#!/usr/bin/env python3
"""Render DejaVu Sans Mono to an anti-aliased (8-bit coverage) bitmap font and
emit `font.rs`.

The bgb debugger uses a small monospace face (courier 9); slopgb owns its
renderer, so we bake a real TTF into a const instead of shipping a font dep.
Each printable ASCII glyph (0x20..0x7E) becomes GLYPH_H rows x GLYPH_W columns
of 8-bit coverage (0 = background, 255 = full ink), row-major flattened to
`[u8; GLYPH_W * GLYPH_H]`. `text::draw_glyph` alpha-blends this over the
destination, so text is smooth instead of 1-bit aliased.

The vertical crop uses the >=128 ink union (the same extent the old 1-bit font
used), so the cell stays GLYPH_W x GLYPH_H and every dialog/menu layout tuned to
those metrics is unaffected — only the glyph rendering gets smoother.

Re-run to regenerate; eyeball the ASCII preview it prints (` .:-=+*#%@` ramp) to
confirm legibility. Reproducible: no randomness.
"""
from PIL import Image, ImageDraw, ImageFont

TTF = "/usr/share/fonts/TTF/DejaVuSansMono.ttf"
SIZE = 12
FIRST, LAST = 0x20, 0x7E
OUT = "crates/slopgb/src/ui/font.rs"

font = ImageFont.truetype(TTF, SIZE)
ascent, descent = font.getmetrics()
CELL = ascent + descent  # scratch height before vertical cropping
# Cell width = the advance of a reference glyph (monospace: all equal).
W = font.getbbox("M")[2]


def render_full(cp):
    """Full-cell 8-bit coverage rows for a code point (W wide, CELL tall)."""
    img = Image.new("L", (W, CELL), 0)
    ImageDraw.Draw(img).text((0, 0), chr(cp), fill=255, font=font)
    return [[img.getpixel((x, y)) for x in range(W)] for y in range(CELL)]


full = {cp: render_full(cp) for cp in range(FIRST, LAST + 1)}
# Crop the cell vertically to the union of rows with any *solid* (>=128) ink, so
# the baked metrics match the previous 1-bit font exactly (no layout shift). AA
# fringe pixels within those rows are preserved; only fully-faint padding rows
# outside the solid extent are dropped.
used = [y for y in range(CELL) if any(full[cp][y][x] >= 128 for cp in full for x in range(W))]
top, bottom = min(used), max(used)
H = bottom - top + 1
glyphs = [(cp, full[cp][top : bottom + 1]) for cp in range(FIRST, LAST + 1)]

# ASCII preview for visual verification (coverage ramped to a character set).
RAMP = " .:-=+*#%@"
print(f"cell {W}x{H}, {len(glyphs)} glyphs")
for cp in (ord("A"), ord("g"), ord("@"), ord("0"), ord("%")):
    rows = dict(glyphs)[cp]
    print(f"--- {chr(cp)!r} ---")
    for row in rows:
        print("".join(RAMP[min(len(RAMP) - 1, v * len(RAMP) // 256)] for v in row))

lines = [
    "//! Embedded monospace bitmap font, generated by `font_gen.py` from",
    "//! DejaVu Sans Mono — do not hand-edit; re-run the generator. Each glyph is",
    "//! `GLYPH_H` rows x `GLYPH_W` columns of 8-bit coverage (0 = background,",
    "//! 255 = full ink), row-major; `text::draw_glyph` alpha-blends it so text is",
    "//! anti-aliased. Metrics match the earlier 1-bit font (no layout shift).",
    "",
    "/// Glyph cell width in pixels.",
    f"pub const GLYPH_W: usize = {W};",
    "/// Glyph cell height in pixels.",
    f"pub const GLYPH_H: usize = {H};",
    "",
    "/// Printable ASCII 0x20..=0x7E: one `[u8; GLYPH_W * GLYPH_H]` coverage map",
    "/// per character, row-major (`row * GLYPH_W + col`).",
    f"pub static GLYPHS: [[u8; GLYPH_W * GLYPH_H]; {len(glyphs)}] = [",
]
for cp, rows in glyphs:
    flat = [v for row in rows for v in row]
    body = ", ".join(f"0x{v:02X}" for v in flat)
    ch = chr(cp).replace("\\", "\\\\")
    comment = "backslash" if cp == 0x5C else f"{ch!r}"
    lines.append(f"    [{body}], // {comment}")
lines.append("];")
lines.append("")
lines += [
    "/// The coverage map for `ch`. Printable ASCII (0x20..=0x7E) maps directly;",
    "/// anything else falls back to `?` so unknown input still renders something.",
    "#[must_use]",
    "pub fn glyph(ch: char) -> &'static [u8; GLYPH_W * GLYPH_H] {",
    "    let c = ch as u32;",
    "    let idx = if (0x20..=0x7E).contains(&c) {",
    "        (c - 0x20) as usize",
    "    } else {",
    "        ('?' as u32 - 0x20) as usize",
    "    };",
    "    &GLYPHS[idx]",
    "}",
    "",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}")
