#!/usr/bin/env python3
"""Render DejaVu Sans Mono to a 1-bpp bitmap font and emit `font.rs`.

The bgb debugger uses a small monospace face (courier 9); slopgb owns its
renderer, so we bake a real TTF into a const instead of shipping a font dep.
Each printable ASCII glyph (0x20..0x7E) becomes GLYPH_H bytes, one per row,
bit 7 = leftmost pixel (GLYPH_W <= 8). Re-run to regenerate; eyeball the ASCII
preview it prints to confirm legibility. Reproducible: no randomness.
"""
from PIL import Image, ImageDraw, ImageFont

TTF = "/usr/share/fonts/TTF/DejaVuSansMono.ttf"
SIZE = 12
FIRST, LAST = 0x20, 0x7E
OUT = "crates/slopgb/src/ui/font.rs"

font = ImageFont.truetype(TTF, SIZE)
ascent, descent = font.getmetrics()
CELL = ascent + descent  # scratch height before vertical cropping
# Cell width = the advance of a reference glyph (monospace: all equal).
W = font.getbbox("M")[2]
assert W <= 8, f"glyph width {W} exceeds one byte"

def render_full(cp):
    img = Image.new("L", (W, CELL), 0)
    ImageDraw.Draw(img).text((0, 0), chr(cp), fill=255, font=font)
    rows = []
    for y in range(CELL):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) >= 128:
                bits |= 1 << (7 - x)
        rows.append(bits)
    return rows

full = {cp: render_full(cp) for cp in range(FIRST, LAST + 1)}
# Crop the cell vertically to the union ink extent across every glyph, so the
# baked font has no dead padding rows (a tighter line height).
used = [y for y in range(CELL) if any(full[cp][y] for cp in full)]
top, bottom = min(used), max(used)
H = bottom - top + 1
glyphs = [(cp, full[cp][top : bottom + 1]) for cp in range(FIRST, LAST + 1)]

# ASCII preview for visual verification.
print(f"cell {W}x{H}, {len(glyphs)} glyphs")
for cp in (ord("A"), ord("g"), ord("@"), ord("0"), ord("%")):
    rows = dict(glyphs)[cp]
    print(f"--- {chr(cp)!r} ---")
    for r in rows:
        print("".join("#" if r & (1 << (7 - x)) else "." for x in range(W)))

lines = [
    "//! Embedded monospace bitmap font, generated by `font_gen.py` from",
    "//! DejaVu Sans Mono — do not hand-edit; re-run the generator. Each glyph is",
    "//! `GLYPH_H` rows, one byte per row, bit 7 = leftmost pixel.",
    "",
    f"/// Glyph cell width in pixels (<= 8, one byte per row).",
    f"pub const GLYPH_W: usize = {W};",
    f"/// Glyph cell height in pixels.",
    f"pub const GLYPH_H: usize = {H};",
    "",
    "/// Printable ASCII 0x20..=0x7E, one `[u8; GLYPH_H]` per character.",
    f"pub static GLYPHS: [[u8; GLYPH_H]; {len(glyphs)}] = [",
]
for cp, rows in glyphs:
    body = ", ".join(f"0x{r:02X}" for r in rows)
    ch = chr(cp).replace("\\", "\\\\")
    comment = "backslash" if cp == 0x5C else f"{ch!r}"
    lines.append(f"    [{body}], // {comment}")
lines.append("];")
lines.append("")
lines += [
    "/// The bitmap rows for `ch`. Printable ASCII (0x20..=0x7E) maps directly;",
    "/// anything else falls back to `?` so unknown input still renders something.",
    "#[must_use]",
    "pub fn glyph(ch: char) -> &'static [u8; GLYPH_H] {",
    "    let c = ch as u32;",
    "    let idx = if (0x20..=0x7E).contains(&c) {",
    "        (c - 0x20) as usize",
    "    } else {",
    "        ('?' as u32 - 0x20) as usize",
    "    };",
    "    &GLYPHS[idx]",
    "}",
    "",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}")
